name: Build and Push Dev Container Image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: devcontainers/ci@v0.3
        with:
          subFolder: src
          imageName: ghcr.io/example/example-devcontainer
          cacheFrom: ghcr.io/example/example-devcontainer
          push: always
